# Install Cypress, then run all tests (in parallel)
stages:
  - test

# Set environment variables for folders in "cache" job settings for npm modules and Cypress binary
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# Cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/*
    - cache/Cypress
    - node_modules
    - build

# Install NPM dependencies and Cypress
# install:
#   image: cypress/browsers:node14.17.0-chrome88-ff89
#   stage: build

#   script:
#     - yarn install --frozen-lockfile
#     # check Cypress binary path and cached versions
#     - npx cypress cache path
#     - npx cypress cache list
#     - yarn types
#     - yarn lint
#     - yarn test:unit:ci
#     - yarn build:ci

api-tests:
  image: cypress/browsers:node14.17.0-chrome88-ff89
  stage: test
  script:
    - yarn add cypress -dev
    - npx cypress run --browser chrome --spec "cypress/integration/Routing.spec.js"
